server:
  port: 8803
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    service-url:
      defaultZone: http://192.168.1.104:30761/eureka
    healthcheck:
      enabled: true
spring:
  application:
    name: SampleService1
