server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${MCLUSTER_IP}:${MCLUSTER_PORT}/eureka

spring:
  application:
    name: MGateway
