server:
  port: 46832
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.11.1.104:30761/eureka

spring:
  application:
    name: MGateway
