server:
  port: 8801
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    service-url:
      defaultZone: http://127.0.0.1:38761/eureka
    healthcheck:
      enabled: true
spring:
  application:
    name: SampleService
