package com.septemberhx.common.log;

import lombok.Getter;
import lombok.Setter;
import org.joda.time.DateTime;

/**
 * @author SeptemberHX
 * @date 2019/8/26
 * @version 0.1
 *
 * Basic log type of services.
 * All the logs will be generated by the MClient module
 */
@Getter
@Setter
public abstract class MServiceBaseLog {
    private DateTime dateTime;  // the date time of the log
    private String objectId;  // the id of the MObject which writes the log
}
