server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka-server-service

mcluster:
  agent:
    name: MCLUSTERAGENT
    ip: 192.168.1.102
    port: 9000