server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    peer-node-read-timeout-ms: 30000


spring:
  application:
    name: eureka-server-service