apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
  namespace: kube-test
  labels:
    app: sample-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
        - name: sample-service
          image: 192.168.1.104:5000/septemberhx/lab2sampleservice:v1.1.1
          ports:
            - containerPort: 8801
      nodeSelector:
        node: "ices-104"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: kube-test
  labels:
    app: sample-service
spec:
  type: NodePort
  ports:
    - port: 8801
      targetPort: 8801
      protocol: TCP
  selector:
    app: sample-service