package com.septemberhx.server.job;

import com.septemberhx.common.bean.MDeployPodRequest;
import com.septemberhx.server.utils.MModelUtils;
import io.kubernetes.client.models.V1Pod;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.UUID;

@Getter
@Setter
@ToString
public class MDeployJob extends MBaseJob {
    private String nodeId;
    private String imageName;
    private String serviceName;
    private String uniqueId;  // to mark the pod with the instance id that generated by the planner

    public MDeployJob(String nodeId, String serviceName, String uniqueId) {
        type = MJobType.DEPLOY;
        this.id = type.toString() + "_" + UUID.randomUUID().toString();
        this.priority = DEPLOY;
        this.nodeId = nodeId;
        this.serviceName = serviceName;
        this.uniqueId = uniqueId;
    }

    public MDeployPodRequest toMDeployPodRequest() {
        return new MDeployPodRequest(id, nodeId, uniqueId, serviceName, imageName);
    }

    public void newId() {
        this.id = type.toString() + "_" + UUID.randomUUID().toString();
    }
}
