server:
  port: 8080
spring:
  application:
    name: MServerApplication
mserver:
  mcluster:
    ip: ${CLUSTER_AGENT_IP}
    port: ${CLUSTER_AGENT_PORT}
  buildcenter:
    ip: ${BUILD_CENTER_IP}
    port: ${BUILD_CENTER_PORT}
  cloudagent:
    ip: ${CLOUD_AGENT_IP}
    port: ${CLOUD_AGENT_PORT}
  deploy:
    dir: /home/hexiang/workspace/idea/MFramework/yaml