apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgateway
  namespace: kube-test
  labels:
    app: mgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgateway
  template:
    metadata:
      labels:
        app: mgateway
    spec:
      containers:
        - name: mgateway
          image: 192.168.1.104:5000/septemberhx/mgateway:v1.1.3
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/log/mclient
              name: log-volume
          env:
            - name: MCLUSTER_IP
              value: "192.168.1.104"
            - name: MCLUSTER_PORT
              value: "30761"
      volumes:
        - name: log-volume
          hostPath:
            path: /data/hexiang/test-dir/log
---
apiVersion: v1
kind: Service
metadata:
  name: mgateway
  namespace: kube-test
  labels:
    app: mgateway
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: mgateway