apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sampleservice2
  generateName: sampleservice2-
spec:
  containers:
    - name: sampleservice2
      image: 192.168.1.104:5000/septemberhx/sampleservice2:v1.1.16
      ports:
        - containerPort: 8802